// Created by Wilson Gramer (https://github.com/Wilsonator5000/SystemColor)

import UIKit

let colors: [(String, UIColor)] = [
    ("label", .label),
    ("secondaryLabel", .secondaryLabel),
    ("tertiaryLabel", .tertiaryLabel),
    ("quaternaryLabel", .quaternaryLabel),
    ("systemFill", .systemFill),
    ("secondarySystemFill", .secondarySystemFill),
    ("tertiarySystemFill", .tertiarySystemFill),
    ("quaternarySystemFill", .quaternarySystemFill),
    ("placeholderText", .placeholderText),
    ("systemBackground", .systemBackground),
    ("secondarySystemBackground", .secondarySystemBackground),
    ("tertiarySystemBackground", .tertiarySystemBackground),
    ("systemGroupedBackground", .systemGroupedBackground),
    ("secondarySystemGroupedBackground", .secondarySystemGroupedBackground),
    ("tertiarySystemGroupedBackground", .tertiarySystemGroupedBackground),
    ("separator", .separator),
    ("opaqueSeparator", .opaqueSeparator),
    ("link", .link),
    ("darkText", .darkText),
    ("lightText", .lightText),
    ("systemBlue", .systemBlue),
    ("systemGreen", .systemGreen),
    ("systemIndigo", .systemIndigo),
    ("systemOrange", .systemOrange),
    ("systemPink", .systemPink),
    ("systemPurple", .systemPurple),
    ("systemRed", .systemRed),
    ("systemTeal", .systemTeal),
    ("systemYellow", .systemYellow),
    ("systemGray", .systemGray),
    ("systemGray2", .systemGray2),
    ("systemGray3", .systemGray3),
    ("systemGray4", .systemGray4),
    ("systemGray5", .systemGray5),
    ("systemGray6", .systemGray6),
]

print("""
// Generated by Wilson Gramer (https://github.com/Wilsonator5000/SystemColor)

import UIKit

/// Use instead of iOS 13's semantic `UIColor`s to provide the light-themed
/// fallback for older versions of iOS. These values are the same as the
/// standard `UIColor` colors as of iOS 13.0 beta 1.
public enum SystemColor {
""")

for (colorName, color) in colors {
    var red: CGFloat = 0
    var green: CGFloat = 0
    var blue: CGFloat = 0
    var alpha: CGFloat = 0
    color.getRed(&red, green: &green, blue: &blue, alpha: &alpha)

    print("""

        public static var \(colorName): UIColor {
            if #available(iOS 13.0, *) {
                return UIColor.\(colorName)
            } else {
                return UIColor(
                    red: \(red),
                    green: \(green),
                    blue: \(blue),
                    alpha: \(alpha)
                )
            }
        }
    """)
}

print("}")

